# Generated by Django 5.0.1 on 2024-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes_order_order_status_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
