# Generated by Django 5.0.1 on 2024-05-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
