# Generated by Django 5.0.1 on 2024-05-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_address_name'),
        ('orders', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
            preserve_default=False,
        ),
    ]
