# Generated by Django 5.0.1 on 2024-05-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_status_delete_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
