# Generated by Django 5.0.1 on 2024-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_products',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
