# Generated by Django 5.0.1 on 2024-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_subtotal_alter_order_total_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_required_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
