# Generated by Django 5.0.1 on 2024-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_coupon_min_required_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='orders.coupon'),
        ),
    ]
