# Generated by Django 5.0.1 on 2024-05-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='min_required_subtotal',
        ),
    ]
