# Generated by Django 5.0.1 on 2024-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_coupon_min_required_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupons',
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_required_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
