# Generated by Django 5.0.1 on 2024-05-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_order_coupons_coupon_min_required_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='min_required_subtotal',
        ),
    ]
