# Generated by Django 5.0.1 on 2024-05-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_address_name'),
        ('orders', '0021_remove_coupon_min_required_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
    ]
