# Generated by Django 5.0.1 on 2024-05-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_coupon_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
    ]
