# Generated by Django 5.0.1 on 2024-05-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_rename_product_coupon_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
