# Generated by Django 5.0.1 on 2024-05-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_orderitem_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='original_price',
        ),
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
