# Generated by Django 5.0.1 on 2024-05-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_orderitem_original_price_order_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
