# Generated by Django 5.0.1 on 2024-05-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_original_price_alter_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_price',
        ),
    ]
