# Generated by Django 5.0.1 on 2024-05-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_rename_product_price_orderitem_orginal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orginal_price',
            new_name='original_price',
        ),
    ]
