# Generated by Django 5.0.1 on 2024-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_rename_orginal_price_orderitem_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='original_price',
        ),
        migrations.AddField(
            model_name='order',
            name='original_price_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
