# Generated by Django 5.0.1 on 2024-05-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_coupon_maximum_amount_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='maximum_amount',
            new_name='minimum_amount',
        ),
    ]
