# Generated by Django 5.0.1 on 2024-05-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_rename_maximum_amount_coupon_minimum_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimum_amount',
            new_name='minimum_required',
        ),
    ]
