# Generated by Django 5.0.1 on 2024-05-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_original_price'),
        ('orders', '0041_rename_minimum_amount_coupon_minimum_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.offer'),
        ),
    ]
