# Generated by Django 5.0.1 on 2024-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_orderitem_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
