# Generated by Django 5.0.1 on 2024-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_order_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_price_total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=20, null=True),
        ),
    ]
