# Generated by Django 5.0.1 on 2024-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_remove_order_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
