# Generated by Django 5.0.1 on 2024-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_order_currency_order_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
