# Generated by Django 5.0.1 on 2024-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_alter_order_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_id',
        ),
    ]
