# Generated by Django 5.0.1 on 2024-05-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_remove_order_currency_remove_order_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_price_total',
        ),
    ]
