# Generated by Django 5.0.1 on 2024-05-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_cancellationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.BooleanField(max_length=100)),
                ('payment_id', models.BooleanField(default=False)),
                ('name', models.BooleanField(default=False)),
            ],
        ),
    ]
