# Generated by Django 5.0.1 on 2024-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_razorpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay',
            name='name',
            field=models.BooleanField(max_length=100),
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='paid',
            field=models.BooleanField(max_length=100),
        ),
    ]
