# Generated by Django 5.0.1 on 2024-05-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_alter_razorpay_name_alter_razorpay_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay',
            name='name',
        ),
    ]
