# Generated by Django 5.0.1 on 2024-05-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_remove_razorpay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='paid',
            field=models.CharField(max_length=100),
        ),
    ]
