# Generated by Django 5.0.1 on 2024-05-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_alter_razorpay_amount_alter_razorpay_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Razorpay',
            new_name='Razorpay_order',
        ),
    ]
