# Generated by Django 5.0.1 on 2024-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_rename_razorpay_razorpay_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
