# Generated by Django 5.0.1 on 2024-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_alter_razorpay_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_order',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
