# Generated by Django 5.0.1 on 2024-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_alter_razorpay_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('razorpay', 'razorpay')], max_length=100),
        ),
    ]
