# Generated by Django 5.0.1 on 2024-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancelled',
        ),
    ]
