# Generated by Django 5.0.1 on 2024-05-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_razorpay_order_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay_order',
            name='order',
        ),
    ]
