# Generated by Django 5.0.1 on 2024-05-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_remove_razorpay_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.razorpay_order'),
        ),
    ]
