# Generated by Django 5.0.1 on 2024-06-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_order_razorpay_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='refunded_amount',
        ),
    ]
