# Generated by Django 5.0.1 on 2024-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_remove_transaction_order_id_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_order',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
