# Generated by Django 5.0.6 on 2024-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_alter_razorpay_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='review_comments',
        ),
    ]
