# Generated by Django 5.0.6 on 2024-06-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_rename_request_recieved_cancellationrequest_request_receieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationrequest',
            old_name='request_receieved',
            new_name='request_recieved',
        ),
    ]
