# Generated by Django 5.0.6 on 2024-06-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_rename_request_receieved_cancellationrequest_request_recieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationrequest',
            old_name='request_recieved',
            new_name='request_received',
        ),
    ]
