# Generated by Django 5.0.6 on 2024-06-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0079_rename_request_recieved_cancellationrequest_request_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='request_received',
        ),
    ]
