# Generated by Django 5.1.4 on 2026-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('razorpay', 'razorpay'), ('wallet', 'Wallet')], max_length=100),
        ),
    ]
