# Generated by Django 5.0.1 on 2024-05-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
