version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /var/www/fruitkha-assets:/app/assets   # Mount static to host
      - /var/www/fruitkha-media:/app/media     # Mount media to host      
    ports:
      - "8090:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d/default.conf
      - /var/www/fruitkha-assets:/var/www/fruitkha-assets
      - /var/www/fruitkha-media:/var/www/fruitkha-media
    depends_on:
      - web

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  postgres_data: