# Generated by Django 5.0.1 on 2024-05-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('home', '0005_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
    ]
