# Generated by Django 5.0.1 on 2024-05-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_offer_category_offer_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
    ]
