# Generated by Django 5.0.1 on 2024-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_category_offer_remove_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
