# Generated by Django 5.0.1 on 2024-05-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_offer_price_alter_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
