# Generated by Django 5.1.4 on 2026-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
